sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.1
  - 2.2.9
  - 2.3.6
  - 2.4.3

before_install: 
  - gem update --system
  - gem --version
  - gem install bundler -v ${BUNDLER_VERSION:-1.16.0}
  - bundle --version
  - mkdir -p tmp/bundle

script: ./bin/test

matrix:
  fast_finish: true

