sudo: false
language: ruby

before_install: 
  - gem update --system  $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION} 
  - bundle --version
  - mkdir -p tmp/bundle

script: ./bin/test

matrix:
  fast_finish: true

matrix:
  include:
    - rvm: 1.9.3
      env: 
      - RUBYGEMS_VERSION=2.7.10
      - BUNDLER_VERSION=1.17.3
    - rvm: 2.0.0
      env: 
      - RUBYGEMS_VERSION=2.7.10
      - BUNDLER_VERSION=1.17.3
    - rvm: 2.1.10
      env: 
      - RUBYGEMS_VERSION=2.7.10
      - BUNDLER_VERSION=1.17.3
    - rvm: 2.2.9
      env: 
      - RUBYGEMS_VERSION=2.7.10
      - BUNDLER_VERSION=1.17.3
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.1
    - rvm: ruby-head
      env: TESTOPTS=-v
  allow_failures:
    - rvm: ruby-head
      env: TESTOPTS=-v

