sudo: false
language: ruby

before_install: 
  - gem update --system  $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler -v ${BUNDLER_VERSION:-1.16.0}
  - bundle --version
  - mkdir -p tmp/bundle

script: ./bin/test

matrix:
  fast_finish: true

matrix:
  allow_failures:
    - rvm: 1.8.7
      gemfile: test/rails_2.3_lts.gemfile
      env: RUBYGEMS_VERSION=1.8.25 RAILS_VERSION=2.3

  include:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1.10
    - rvm: 2.2.9
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.8.1
